// types of redux actions
export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const BOOKMARK_REPO = 'BOOKMARK_REPO';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';